# Ultralytics 🚀 AGPL-3.0 License - https://ultralytics.com/license
"""
Ultralytics neural network modules.

This module provides access to various neural network components used in Ultralytics models, including convolution
blocks, attention mechanisms, transformer components, and detection/segmentation heads.

Examples:
    Visualize a module with Netron
    >>> from ultralytics.nn.modules import Conv
    >>> import torch
    >>> import subprocess
    >>> x = torch.ones(1, 128, 40, 40)
    >>> m = Conv(128, 128)
    >>> f = f"{m._get_name()}.onnx"
    >>> torch.onnx.export(m, x, f)
    >>> subprocess.run(f"onnxslim {f} {f} && open {f}", shell=True, check=True)  # pip install onnxslim
"""

from .block import (
    C3k2_Dynamic,
    C3k2UltraPro,
    C3k2MA,
    C3k2MA_Lite,
    C2f_LSKA,
    WaveC2f,
    DyC2f,
    A3C2f,
    MP,
    SP,
    C1,
    C2,
    C2PSA,
    C3,
    C3TR,
    CIB,
    DFL,
    PSA,
    SPP,
    SPPF,
    v10_Attention,
    BNContrastiveHead,
    Bottleneck,
    CSPNeXtBlock,
    BottleneckCSP,
    BottleneckCSP2,
    BottleneckCSPA,
    BottleneckCSPB, 
    BottleneckCSPC,
    C2f,
    RTMBlock,
    C2fAttn,
    C2fCIB,
    C2fPSA,
    C3Ghost,
    C3k2,
    C3x,
    ContrastiveHead,
    GhostBottleneck,
    HGBlock,
    HGStem,
    ImagePoolingAttn,
    Proto,
    RepC3,
    RepVGGDW,
    ResNetLayer,
    SCDown,
    RepNCSPELAN4_low,
    RepNCSPELAN4_high,
    SPPCSP,
    SPPCSPC,
    SPPFCSPC,
    DepthSepConv,
    C2f_DCN, 
    C3_DCN, 
    DCNv2,
    SimFusion_4in, 
    SimFusion_3in, 
    InjectionMultiSum_Auto_pool,
    PyramidPoolAgg,
    TopBasicLayer, 
    AdvPoolFusion, 
    IFM, 
    Shortcut, 
    DownC,
    SimSPPF,
    SimConv,
    RepBlock,
    RepVGGBlock,
    Transpose,
    CBH,
    LC_Block,
    Dense,
    conv_bn_relu_maxpool,
    Shuffle_Block,
    DWConvblock,
    CPCAChannelAttention,
    C3C2,
    LayerNorm_s,
    ConvNextBlock,
    CNeB,
    GAMAttention,
    Res,
    ResCSPA,
    ResCSPB,
    ResCSPC,
    ResXCSPA,
    ResXCSPB,
    ResXCSPC,
    SegNext_Attention,
    LayerNormProxy,
    DAttention,
    ShuffleAttention,
    ES_SEModule,
    ES_Bottleneck, 
    DepthWiseConv,
    PointWiseConv,
    MobileOneBlock,
    MobileOne,
    HorLayerNorm,
    gnconv,
    HorBlock,
    CrissCrossAttention,
    SEAttention,
    SKAttention,
    ECAAttention,
    EffectiveSE,
    BasicConv,
    ZPool,
    AttentionGate,
    TripletAttention,
    Bottleneck_TripletAt,
    C2f_TripletAt,
    C3_TripletAt,
    DeformConv,
    deformable_LKA,
    deformable_LKA_Attention,
    Bottleneck_DLKA,
    C2f_DLKA,
    C3_DLKA,
    SELayer,
    conv_bn_hswish,
    MobileNetV3_InvertedResidual,
    mobilev3_bneck,
    SimAM,
    RepConvN,
    RepNCSPELAN4,
    SPPELAN,
    CBLinear,
    CBFuse, 
    ADown,
    OREPANBottleneck,
    OREPANCSP,
    OREPANCSPELAN4,
    RepNCSP_AKConv,
    RepNCSPELAN4AKConv, 
    KANRepNCSPELAN4,
    FasterRepNCSPELAN4,
    PRepNCSPELAN4,
    PConv,
    DCNV3_YoLo,
    DCNV3RepNCSPELAN4,
    Bottleneck_DCNV3,
    C2f_DCNV3,
    Yolov7_Tiny_E_ELAN,
    Yolov7_Tiny_SPP,
    Yolov7_Tiny_E_ELANMO,
    Yolov7_E_ELAN,
    V7DownSampling,
    MobileOneBlock_origin,
    MobileOne_origin,
    MHSA,
    BottleneckTransformer,
    BoT3,
    ADD,
    ELAN1,
    CoordAtt,
    CARAFE,
    LSKblock,
    FocusedLinearAttention,
    Bottleneck_FLA,
    C2f_FLA,
    PSAFLA,
    ASPP,
    Bottleneck_Dual,
    C2f_Dual,
    Bottleneck_WT,
    C2f_WT,
    BasicConv,
    BasicRFB,
    Light_HGBlock,
    LSKA,
    EMA,
    SDFM,
    AAttn,
    ABlock,
    A2C2f,
    CSP_EIMS,
    HRIF,
    HyperACE, 
    DownsampleConv, 
    FullPAD_Tunnel,
    DSC3k2,
    TorchVision,
    MFAM,
    IEMA,
    DASI,
    PST,
)
from .ppyolo import (
    ResSPP,
    CSPResNet,
    CSPResNet_CBS,
    ConvBNLayer,
    CSPResStage,
    RepVggBlock,
    EffectiveSELayer,
    BasicBlock,
)
from .conv import (
    CBAM,
    ChannelAttention,
    Concat,
    Conv,
    Conv_BCN,
    FDConv_cfg,
    DualConv,
    Conv2,
    ConvTranspose,
    DWConv,
    DWConvTranspose2d,
    Focus,
    GhostConv,
    LightConv,
    RepConv,
    SpatialAttention,
    RepConv_v7,
    ReOrg,
    CAConv,
    ImplicitA,
    ImplicitM,
    AKConv,
    ODConv2d_3rd,
    ODConv_3rd,
    ConvNextBlock,
    LayerNorm_s,
    DropPath,
    AConv,
    CoordConv,
    RFAConv,
    RFCBAMConv,
    RFCAConv,
    SPDConv,
    LDConv,
    Conv_DynamicTanh,
    FCM, 
    Pzconv,  
    FCM_3,
    FCM_2, 
    FCM_1, 
    Down,
    DSConv,
    Index,
)
from .head import (
    OBB,
    MAFOBB,
    IOBB,
    OBB26,
    Classify,
    Detect,
    MAFDetect,
    IDetect,
    LRPCHead,
    Pose,
    MAFPose,
    IPose,
    Pose26,
    RTDETRDecoder,
    Segment,
    MAFSegment,
    ISegment,
    Segment26,
    WorldDetect,
    YOLOEDetect,
    YOLOESegment,
    YOLOESegment26,
    v10Detect,
)
from .transformer import (
    AIFI,
    MLP,
    DeformableTransformerDecoder,
    DeformableTransformerDecoderLayer,
    LayerNorm2d,
    MLPBlock,
    MSDeformAttn,
    TransformerBlock,
    TransformerEncoderLayer,
    TransformerLayer,
)
from .damoyolo import CSPStage
from .DySample import DySample
from .repvit import RepViTBlock
from .ContextGuided import C2f_Context, ContextGuidedBlock_Down
from .MSDA import MultiDilatelocalAttention, PSAMSDA, C2PSA_MSDA
from .biformer import BiLevelRoutingAttention
from .DiverseBranch import DiverseBranchBlock, C2f_DBB
from .SEAM import SEAM, MultiSEAM
from .FFANet import FFA
from .TaylorFormer import MB_TaylorFormer
from .CPA import CPA_arch
from .iRMB import iRMB, C2f_iRMB
from .Haar import Down_wt
from .HAttention import HAT
from .Retinexformer import RetinexFormer
from .SCConv import C2f_SCConv, ScConv
SCConv = ScConv  # alias for YAML compatibility
from .C2fGhostModuleDynamicConv import C2f_GhostModule_DynamicConv, DynamicConv, C2f_DynamicConv
from .ODConv import C2f_ODConv, ODConv2d
from .DWR import C2f_DWRSeg
from .SAConv import SAConv2d, C2f_SAConv, C3k2_SAConv
from .MSBlock import C2f_MSBlock, C2f_MSBlockv2
from .OREPA import OREPA, C3_OREPA, C2f_OREPA
from .OREPA_2 import OREPA_2, C3k2_OREPA_backbone, C3k2_OREPA_neck
from .IAT import IAT
from .FasterBlock import C2f_FasterBlock, C2f_FasterBlock_EMA, C3_Faster_CGLU, C2f_Faster_CGLU, C3k2_FasterBlock
C2f_Faster_EMA = C2f_FasterBlock_EMA  # alias for YAML compatibility
from .SENetV1 import C2f_SENetV1, SELayerV1
from .SENetV2 import C2f_SENetV2, SELayerV2, PSASENetV2, C2PSA_SENetV2, SPPFSENetV2
from .Slimneck import VoVGSCSP, GSConv
from .Slimneckv2 import SNI, GSConvE, GSConvE2, ESD, ESD2
from .RCSOSA import RepVGG, RCSOSA, C3k2_RepVGG
from .BiFPN import Bi_FPN
from .RIDNet import RIDNET
from .ADNet import ADNet
from .leyolo import mn_conv, InvertedBottleneck, MobileNetV3_BLOCK
from .CSPHet import CSPHet
from .CSPPC import CSPPC
from .FocalModulation import FocalModulation
from .ASFyolo import Zoom_cat, Add, ScalSeq, attention_model
from .EVC import EVCBlock
from .DSConv_module import C2f_DSConv, DSConv2D
from .VanillaNet import VanillaStem, VanillaBlock
from .StarNet import C3_Star, C3_Star_CAA, C2f_Star, C2f_Star_CAA
from .EffectiveSE import C3_EMBC, C2f_EMBC
from .block import EffectiveSE  # re-import after submodule import
from .EMSC import C3_EMSC, C2f_EMSC, C3_EMSCP, C2f_EMSCP
from .DilatedReparam import C3_UniRepLKNetBlock, C2f_UniRepLKNetBlock, C3_DRB, C2f_DRB, DilatedReparamBlock, UniRepLKNetBlock
from .DA import C2f_DAttention, C2PSA_DAT, DAttentionBaseline
from .mobileone import MobileOnev5, MobileOneBlockv5
from .RetNet import C3_RetBlock, C2f_RetBlock
from .REPVGGOREPA import C3_REPVGGOREPA, C2f_REPVGGOREPA
from .RFAConv import RFAConv, C3_RFAConv, C2f_RFAConv, C3_RFCBAMConv, C2f_RFCBAMConv, C3_RFCAConv, C2f_RFCAConv
from .RVB import C3_RVB, C2f_RVB, C3_RVB_EMA, C2f_RVB_EMA
from .UIB import C2f_UIB, C3k2_UIB
from .SwinTransformer import PatchMerging, PatchEmbed, SwinStage
from .BiFPN import Concat_BiFPN
from .ConvNeXtv2 import C3k2_ConvNeXtV2Block, C3k_ConvNeXtV2Block
from .WTConv import C3k2_WTConv
from .LAE import LAE
from .KAN import RBFKANConv2d, ReLUKANConv2d, KANConv2d, FasterKANConv2d, WavKANConv2d, ChebyKANConv2d, JacobiKANConv2d, FastKANConv2d, GRAMKANConv2d
from .EfficientNet import stem, MBConvBlock
from .CGA import C2PSA_CGA, LocalWindowAttention
from .MLLABLock import C3k2_MLLABlock1, C3k2_MLLABlock2
from .MLLA import C2fMLLABlock
from .MLLA_2 import C2PSAMLLA
from .DiT import DiTBlock, C2PSA_DiTBlock, C3k2_DiTBlock
from .mafyolo import RepHDW, AVG, RepHMS, ConvMS, UniRepLKNetBlock_pro
from .cstyolo import MyConcat4, MyConcat6, CST, MCS
from .hyperyolo import MANet, HyperComputeModule, HyperComputeModule_11
from .ALSSyolo import LCA, ALSS
from .MSCAM import EMCAD_block, MSCAM, MSCAMv2, MSCAMv3, MSCAMv4, MSCAMv5
from .UNetv2 import pvt_v2_b0, pvt_v2_b1, pvt_v2_b2, pvt_v2_b3, pvt_v2_b4, pvt_v2_b5
from .MobileNetv1 import MobileNetV1
from .MobileNetv2 import MobileNetV2_n, MobileNetV2_s, MobileNetV2_m
from .MobileNetv3 import MobileNetV3_large_n, MobileNetV3_large_s, MobileNetV3_large_m, MobileNetV3_small_n, MobileNetV3_small_s, MobileNetV3_small_m
from .MobileNetv4 import MobileNetV4ConvLarge, MobileNetV4ConvSmall, MobileNetV4ConvMedium, MobileNetV4HybridMedium, MobileNetV4HybridLarge
from .MobileViTv1 import mobile_vit_xx_small, mobile_vit_x_small, mobile_vit_small
from .MobileViTv2 import mobile_vit2_xx_small
from .EfficientNetV1_backbone import efficient
from .EfficientNetV2 import efficientnet_v2
from .GhostNetv1 import Ghostnetv1
from .GhostNetv2 import GhostNetV2, Ghostnetv2
from .GhostNetv3 import GhostNet_1_0
from .ConvNeXtV2_backbone import convnextv2_atto, convnextv2_femto, convnext_pico, convnextv2_nano, convnextv2_tiny, convnextv2_base, convnextv2_large, convnextv2_huge
from .ConvNeXtV1 import convnext_tiny, convnext_small, convnext_base, convnext_large, convnext_xlarge
from .EfficientViT_microsoft import EfficientViT_M0, EfficientViT_M1, EfficientViT_M2, EfficientViT_M3, EfficientViT_M4, EfficientViT_M5
from .EfficientViT_MIT import efficientvit_backbone_b0, efficientvit_backbone_b1, efficientvit_backbone_b2, efficientvit_backbone_b3
from .RepViT_backbone import repvit_m0_6, repvit_m0_9, repvit_m1_0, repvit_m1_1, repvit_m1_5, repvit_m2_3, RepViT
from .StarNet_backbone import starnet_s050, starnet_s100, starnet_s150, starnet_s1, starnet_s2, starnet_s3, starnet_s4
from .FasterNet import fasternet_t0, fasternet_t1, fasternet_t2, fasternet_s, fasternet_m, fasternet_l
from .RepLKNet import RepLKNet31B, RepLKNet31L, RepLKNetXL
from .UniRepLknet import unireplknet_a, unireplknet_f, unireplknet_p, unireplknet_n, unireplknet_t, unireplknet_s, unireplknet_b, unireplknet_l, unireplknet_xl, UniRepLKNet
from .LSKNet import LSKNET_T, LSKNET_S
from .MogaNet_backbone import moganet_xtiny, moganet_tiny, moganet_small, moganet_base, moganet_large, moganet_xlarge
from .VanillaNet_backbone import vanillanet_5, vanillanet_6, vanillanet_7, vanillanet_8, vanillanet_9, vanillanet_10, vanillanet_11, vanillanet_12, vanillanet_13, vanillanet_13_x1_5, vanillanet_13_x1_5_ada_pool, VanillaNet
from .MambaOut import mambaout_femto, mambaout_kobe, mambaout_tiny, mambaout_small, mambaout_base
from .RMT import RMT_T, RMT_S, RMT_B, RMT_L
from .RevCol import revcol_tiny, revcol_small, revcol_base, revcol_large, revcol_xlarge
from .SwinTransformer_backbone import SwinTransformer_Tiny, SwinTransformer_Tiny_c24, SwinTransformer_Small, SwinTransformer_Base, SwinTransformer_Large
from .SwinTransformerv2_backbone import swin_transformer_v2_t, swin_transformer_v2_s, swin_transformer_v2_b, swin_transformer_v2_l, swin_transformer_v2_h, swin_transformer_v2_g
from .SwinTransformer_Mona_backbone import SwinTransformer_mona_Tiny, SwinTransformer_mona_Small, SwinTransformer_mona_Base, SwinTransformer_mona_Large
from .SlabSwinTransformer import SlabSwinTransformer_T, SlabSwinTransformer_S, SlabSwinTransformer_B
from .EMO import EMO_1M, EMO_2M, EMO_5M, EMO_6M
from .EMOv2 import EMO2_1M_k5_hybrid, EMO2_1M_k5_hybrid_256, EMO2_1M_k5_hybrid_512, EMO2_2M_k5_hybrid, EMO2_2M_k5_hybrid_256, EMO2_2M_k5_hybrid_512, EMO2_5M_k5_hybrid, EMO2_5M_k5_hybrid_256, EMO2_5M_k5_hybrid_512, EMO2_20M_k5_hybrid, EMO2_20M_k5_hybrid_256, EMO2_50M_k5_hybrid
from .ShuffleNetV1 import ShuffleNetG1, ShuffleNetG2, ShuffleNetG3, ShuffleNetG4, ShuffleNetG8
from .ShuffleNetV2 import shufflenetv2_05, shufflenetv2_10, shufflenetv2_15, shufflenetv2_20
from .VGG_backbone import VGG11, VGG13, VGG16, VGG19
from .ResNet_backbone import ResNet18, ResNet34, ResNet50, ResNet101, ResNet152
from .ResNet_MoE import resnet18_moe, resnet34_moe, resnet50_moe, resnet101_moe, resnet152_moe
from .LAUDNet import uni_resnet50, uni_resnet101
from .EPSANet import epsanet50, epsanet101 
from .SA_Net import sa_resnet50, sa_resnet101, sa_resnet152
from .MSPANet import mspanet50, mspanet101
from .OrthoNet import orthonet34, orthonet50, orthonet101, orthonet152
from .KW_ResNet import kw_resnet18, kw_resnet50
from .OverLoCK import overlock_xt, overlock_t, overlock_s, overlock_b, OverLoCK
from .RDNet import rdnet_tiny, rdnet_small, rdnet_base, rdnet_large
from .SMT import smt_t, smt_s, smt_b, smt_l
from .GroupMixFormer import GroupMixFormerMiny, GroupMixFormerTiny, GroupMixFormerSmall, GroupMixFormerBase, GroupMixFormerLarge
from .PolaFormer import pola_pvt_tiny, pola_pvt_small, pola_pvt_medium, pola_pvt_large
from .NextViT import nextvit_small, nextvit_base, nextvit_large 
from .FocalNet import focalnet_tiny_srf, focalnet_tiny_lrf, focalnet_small_srf, focalnet_small_lrf, focalnet_base_srf, focalnet_base_lrf, focalnet_large_fl3, focalnet_large_fl4, focalnet_xlarge_fl3, focalnet_xlarge_fl4, focalnet_huge_fl3, focalnet_huge_fl4
from .PoolFormer import poolformer_s12, poolformer_s24, poolformer_s36, poolformer_m48, poolformer_m36
from .InceptionNext import inceptionnext_tiny, inceptionnext_small, inceptionnext_base, inceptionnext_base_384
from .FastViT import fastvit_t8, fastvit_t12, fastvit_s12, fastvit_sa12, fastvit_sa24, fastvit_sa36, fastvit_ma36, FastViT
from .NFNet import NFNetF0, NFNetF1, NFNetF2, NFNetF3, NFNetF4, NFNetF5, NFNetF6, NFNetF7 
from .DFormerv2 import DFormerv2_S, DFormerv2_B, DFormerv2_L
from .DFFormer import dfformer_s18, dfformer_s36, dfformer_m36, dfformer_b36, gfformer_s18, cdfformer_s18, cdfformer_s36, cdfformer_m36, cdfformer_b36, dfformer_s18_gelu, dfformer_s18_relu, dfformer_s18_k2, dfformer_s18_d8, dfformer_s18_afno
from .ParameterNet import GhostNet_Reparam
from .EfficientFormerV2 import efficientformerv2_s0, efficientformerv2_s1, efficientformerv2_s2, efficientformerv2_l
from .EdgeViT import EdgeVitXXS, EdgeVitXS, EdgeVitS
from .GreedyViG import GreedyViG_S, GreedyViG_M, GreedyViG_B
from .MobileViGv2 import mobilevigv2_ti, mobilevigv2_s, mobilevigv2_m, mobilevigv2_b, MobileViG
from .UniFormer import uniformer_light_xxs, uniformer_light_xs
from .SwiftFormer import SwiftFormer_XS, SwiftFormer_S, SwiftFormer_L1, SwiftFormer_L3
from .PVTv2 import pvtv2_b0, pvtv2_b1, pvtv2_b2, pvtv2_b2_li, pvtv2_b3, pvtv2_b4, pvtv2_b5
from .SlabPVTv2 import slab_pvt_v2_b0, slab_pvt_v2_b1, slab_pvt_v2_b2, slab_pvt_v2_b2_li, slab_pvt_v2_b3, slab_pvt_v2_b4, slab_pvt_v2_b5
from .Conv2Former import conv2former_n, conv2former_t, conv2former_s, conv2former_b, conv2former_b_22k, conv2former_l
from .LWGANet import LWGANet_L0_1242_e32_k11_GELU, LWGANet_L1_1242_e64_k11_GELU, LWGANet_L2_1442_e96_k11_ReLU
from .HorNet import hornet_tiny_7x7, hornet_tiny_gf, hornet_small_7x7, hornet_small_gf, hornet_base_7x7, hornet_base_gf, hornet_base_gf_img384, hornet_large_7x7, hornet_large_gf, hornet_large_gf_img384
from .EfficientViM import EfficientViM_M1, EfficientViM_M2, EfficientViM_M3, EfficientViM_M4
from .SHViT import SHViT_S1, SHViT_S2, SHViT_S3, SHViT_S4
from .CAS_ViT import RCViT_XS, RCViT_S, RCViT_M, RCViT_T
from .GCViT import gc_vit_xxtiny, gc_vit_xtiny, gc_vit_tiny, gc_vit_tiny2, gc_vit_small, gc_vit_small2, gc_vit_base, gc_vit_large, gc_vit_large_224_21k, gc_vit_large_384_21k, gc_vit_large_512_21k
from .ConViT import convit_tiny_backbone, convit_small_backbone, convit_base_backbone
from .RepVGG_backbone import RepVGG_A0, RepVGG_A1, RepVGG_A2, RepVGG_B0, RepVGG_B1, RepVGG_B1g2, RepVGG_B1g4, RepVGG_B2, RepVGG_B2g2, RepVGG_B2g4, RepVGG_B3, RepVGG_B3g2, RepVGG_B3g4, RepVGG_D2se, RepVGGBlock
from .QARepVGG import QARepVGG_A0, QARepVGGV1_A0, QARepVGGV2_A0, QARepVGGV2_A0_d01, QARepVGGV2_A0_DW, QARepVGGV6_A0, QARepVGG_A0_ReLU6, QARepVGGV2_A0_PReLU, QARepVGGV2_A1, QARepVGGV2_A2, QARepVGGV2_B0, QARepVGGV2_B1, QARepVGGV2_B1g2, QARepVGGV2_B1g4, QARepVGGV2_D2se, QARepVGGBlock
from .DecoupleNet import decouplenet_d0, decouplenet_d1, decouplenet_d2
from .SBCFormer import sbcformer_xs, sbcformer_s, sbcformer_b, sbcformer_l
from .FaNet import fanet_tiny, fanet_small
from .COSNet import cosnet_tiny, cosnet_small, cosnet_base
from .WTConvNeXt import wtconvnext_tiny, wtconvnext_small, wtconvnext_base, wtconvnext_large, wtconvnext_xlarge
from .MLLA_backbone import MLLA_Tiny, MLLA_Small, MLLA_Base
from .PKINet import pkinet_t, pkinet_s, pkinet_b
from .GLNet import glnet_stl, glnet_stl_paramslot, glnet_4g, glnet_9g, glnet_16g
from .RAVLT import RAVLT_T, RAVLT_S, RAVLT_B, RAVLT_L
from .SLaK import slak_tiny, slak_small, slak_base, slak_large
from .SVT import svt_s, svt_b, svt_l
from .EViT import EViT_Tiny, EViT_Small, EViT_Base, EViT_Large
from .SGFormer import sgformer_s, sgformer_m, sgformer_b
from .SPANet import spanet_s, spanet_m, spanet_mx, spanet_b, spanet_bx
from .StripMLPNet import StripMLPNet_LightTiny, StripMLPNet_Tiny, StripMLPNet_Small, StripMLPNet_Base
from .MetaFormer import identityformer_s12, identityformer_s24, identityformer_s36, identityformer_m36, identityformer_m48, randformer_s12, randformer_s24, randformer_s36, randformer_m36, randformer_m48, poolformerv2_s12, poolformerv2_s24, poolformerv2_s36, poolformerv2_m36, poolformerv2_m48, convformer_s18, convformer_s36, convformer_m36, convformer_b36, caformer_s18, caformer_s36, caformer_m36, caformer_b36
from .iFormer import iformer_small, iformer_base, iformer_large
from .VAN import van_b0, van_b1, van_b2, van_b3, van_b4, van_b5, van_b6
from .vHeat import vheat_tiny, vheat_small, vheat_base
from .vHeat_MoE import vHeat_MoE_t, vHeat_MoE_s, vHeat_MoE_b
from .LSNet import LSNet_T, LSNet_S, LSNet_B
from .StripNet import StripNet_tiny, StripNet_small
from .TransXNet import transxnet_tiny, transxnet_small, transxnet_base
from .TransNeXt import transnext_micro, transnext_tiny, transnext_small, transnext_base
from .ParCNetV2 import parcnetv2_xt, parcnetv2_tiny, parcnetv2_small, parcnetv2_base
from .MALA import MALA_T, MALA_S, MALA_B, MALA_L
from .MPViT import mpvit_tiny, mpvit_xsmall, mpvit_small, mpvit_base
from .UniNeXt import uninext_t, uninext_s, uninext_b
from .STViT import stvit_small, stvit_base, stvit_large
from .FAT import fat_b0, fat_b1, fat_b2, fat_b3
from .DeBiFormer import debi_tiny, debi_small, debi_base
from .MaxViT import maxvit_tiny, maxvit_small, maxvit_base, maxvit_large
from .ScalableViT import scalable_vit_s, scalable_vit_b, scalable_vit_l
from .ResTv1 import rest_lite, rest_small, rest_base, rest_large
from .ResTv2 import restv2_tiny, restv2_small, restv2_base, restv2_large
from .MedFormer import medformer_tiny, medformer_small, medformer_base
from .TinyViT import tiny_vit_5m, tiny_vit_11m, tiny_vit_21m
from .PartialNet import partialnet_s, partialnet_m, partialnet_l
from .WaveFormer import waveformer_tiny, waveformer_small, waveformer_base
# Modular ------------------------------------------------------------
from .FasterNet_modular import PatchEmbed_Faster, PatchMerging_Faster, FasterNetLayer
from .PartialNet_modular import Partial_PatchEmbed, Partial_Block, Partial_Downsample 
from .ParCNetV2_modular import ParCDown, ParCBlock
from .StripNet_modular import StripDownsample, StripBlock
from .MogaNet_modular import StackConvPatchEmbed, MogaStage, ConvPatchEmbed
from .vHeat_modular import vHeatStem, vHeatStage, vHeatDownsample
# Modular ------------------------------------------------------------
# Deformable ----------------------------------------------
from .FlashInternImage import flash_intern_image_t, flash_intern_image_s, flash_intern_image_b
from .DSAN import dsan_t, dsan_s, dsan_b
from .GSPN import gspn_tiny, gspn_small, gspn_base
# Deformable ----------------------------------------------
from .HVI_CIDNet import C2PSA_HV_LCA, C2PSA_HV_LCA_DynamicTanh, LCA_Concat, LCA_DynamicTanh_Concat
from .MogaNet import C2f_MultiOGA, ChannelAggregationFFN, MultiOrderGatedAggregation
from .AgentAttention import C2PSA_Agent
from .KSFA import C2PSA_KS
from .FDConv import FDConv
from .DySnakeConv import DySnakeConv, C3k2_DSConv, DySnakeRepNCSPELAN4
from .SFSConv import SFS_Conv
from .F2SoftHG import F2SoftHG, ShapeAlignConv, MergeConv
from .upsample_anything import UPA 
from .MambaNeXt import MambaNeXt, IRDCB
# from .moe import OptimizedMOE, OptimizedMOEImproved, MOE, ES_MOE, EfficientSpatialRouterMoE, ModularRouterExpertMoE, UltraOptimizedMoE, AdaptiveCapacityMoE, HyperSplitMoE, HyperFusedMoE, HyperUltimateMoE, UltimateOptimizedMoE
from .vajra import VajraV1MerudandaX, VajraV1AttentionBhag6, VajraV1MerudandaBhag15

from .moe import (
    OptimizedMOE,
    OptimizedMOEImproved,
    MOE,
    ES_MOE,
    EfficientSpatialRouterMoE,
    ModularRouterExpertMoE,
    UltraOptimizedMoE,
    AdaptiveCapacityMoE,
    HyperSplitMoE,
    HyperFusedMoE,
    HyperUltimateMoE,
    UltimateOptimizedMoE,
    A2C2fMoE,
    ABlockMoE,
)

__all__ = (
    "C3k2_Dynamic",
    "C3k2UltraPro",
    "C3k2MA",
    "C3k2MA_Lite",
    "C2f_LSKA",
    "WaveC2f",
    "DyC2f",
    "A3C2f",
    "OptimizedMOE",
    "OptimizedMOEImproved",
    "MOE",
    "EfficientSpatialRouterMoE",
    "ModularRouterExpertMoE",
    "ES_MOE",
    "UltraOptimizedMoE",
    "AdaptiveCapacityMoE",
    "HyperSplitMoE",
    "HyperFusedMoE",
    "HyperUltimateMoE",
    "UltimateOptimizedMoE",
    "A2C2fMoE",
    "ABlockMoE",
    "OBB26",
    "Pose26",
    "Segment26",
    "YOLOESegment26",
    
    "MP",
    "SP",
    "Conv",
    "Conv_BCN",
    "FDConv",
    "FDConv_cfg",
    "DualConv",
    "Conv2",
    "LightConv",
    "RepConv",
    "DWConv",
    "DWConvTranspose2d",
    "ConvTranspose",
    "Focus",
    "GhostConv",
    "ChannelAttention",
    "SpatialAttention",
    "CBAM",
    "Concat",
    "TransformerLayer",
    "TransformerBlock",
    "MLPBlock",
    "LayerNorm2d",
    "DFL",
    "HGBlock",
    "HGStem",
    "SPP",
    "SPPF",
    "C1",
    "C2",
    "C3",
    "C2f",
    "RTMBlock",
    "C3k2",
    "SCDown",
    "C2fPSA",
    "C2PSA",
    "C2fAttn",
    "C3x",
    "C3TR",
    "C3Ghost",
    "GhostBottleneck",
    "Bottleneck",
    "CSPNeXtBlock",
    "BottleneckCSP",
    "BottleneckCSP2",
    "BottleneckCSPA", 
    "BottleneckCSPB", 
    "BottleneckCSPC",
    "Proto",
    "Detect",
    "Segment",
    "Pose",
    "Classify",
    "TransformerEncoderLayer",
    "RepC3",
    "RTDETRDecoder",
    "AIFI",
    "DeformableTransformerDecoder",
    "DeformableTransformerDecoderLayer",
    "MSDeformAttn",
    "MLP",
    "ResNetLayer",
    "OBB",
    "WorldDetect",
    "v10Detect",
    "ImagePoolingAttn",
    "ContrastiveHead",
    "BNContrastiveHead",
    "RepVGGDW",
    "CIB",
    "C2fCIB",
    "v10_Attention",
    "PSA",
    "RepConv_v7",
    "ReOrg",
    "SPPCSP",
    "SPPCSPC",
    "SPPFCSPC",
    "SEBlock", 
    "DepthSepConv",
    "C2f_DCN", 
    "C3_DCN", 
    "DCNv2",
    "SimFusion_4in", 
    "SimFusion_3in", 
    "InjectionMultiSum_Auto_pool", 
    "PyramidPoolAgg",
    "TopBasicLayer", 
    "AdvPoolFusion", 
    "IFM", 
    "Shortcut", 
    "DownC",
    "SimSPPF",
    "SimConv",
    "RepBlock",
    "RepVGGBlock",
    "Transpose",
    "CBH",
    "LC_Block",
    "Dense",
    "conv_bn_relu_maxpool",
    "Shuffle_Block",
    "DWConvblock",
    "CPCAChannelAttention",
    "C3C2",
    "LayerNorm_s",
    "ConvNextBlock",
    "CNeB",
    "GAMAttention",
    "Res",
    "ResCSPA",
    "ResCSPB",
    "ResCSPC",
    "ResXCSPA",
    "ResXCSPB",
    "ResXCSPC",
    "SegNext_Attention",
    "LayerNormProxy",
    "DAttention",
    "ShuffleAttention",
    "ES_SEModule",
    "ES_Bottleneck", 
    "DepthWiseConv",
    "PointWiseConv",
    "MobileOneBlock",
    "MobileOne",
    "HorLayerNorm",
    "gnconv",
    "HorBlock",
    "CrissCrossAttention",
    "SEAttention",
    "SKAttention",
    "ECAAttention",
    "EffectiveSE",
    "CAConv",
    "BasicConv",
    "ZPool",
    "AttentionGate",
    "TripletAttention",
    "Bottleneck_TripletAt",
    "C2f_TripletAt",
    "C3_TripletAt",
    "DeformConv",
    "deformable_LKA",
    "deformable_LKA_Attention",
    "Bottleneck_DLKA",
    "C2f_DLKA",
    "C3_DLKA",
    "SELayer",
    "conv_bn_hswish",
    "MobileNetV3_InvertedResidual",
    "mobilev3_bneck",
    "ImplicitA",
    "ImplicitM",
    "IDetect",
    "ISegment",
    "IOBB",
    "IPose",
    "RepConvN",
    "RepNCSPELAN4",
    "RepNCSPELAN4_low",
    "RepNCSPELAN4_high",
    "SPPELAN",
    "CBLinear",
    "CBFuse", 
    "ADown",
    "DDetect",
    "DOBB",
    "DSegment",
    "DPose",
    "OREPANBottleneck",
    "OREPANCSP",
    "OREPANCSPELAN4",
    "SimAM",
    "ResSPP",
    "CSPResNet",
    "CSPResNet_CBS",
    "ConvBNLayer",
    "CSPResStage",
    "RepVggBlock",
    "EffectiveSELayer",
    "BasicBlock",
    "AKConv",
    "RepNCSP_AKConv",
    "RepNCSPELAN4AKConv", 
    "KANRepNCSPELAN4",
    "FasterRepNCSPELAN4",
    "PRepNCSPELAN4",
    "PConv",
    "DCNV3_YoLo",
    "DCNV3RepNCSPELAN4",
    "Bottleneck_DCNV3",
    "C2f_DCNV3",
    "ODConv2d_3rd",
    "ODConv_3rd",
    "ConvNextBlock",
    "LayerNorm_s",
    "DropPath",
    "ScConv",
    "Yolov7_Tiny_E_ELAN",
    "Yolov7_Tiny_SPP",
    "Yolov7_Tiny_E_ELANMO",
    "Yolov7_E_ELAN",
    "V7DownSampling",
    "MobileOneBlock_origin",
    "MobileOne_origin",
    "MHSA",
    "BottleneckTransformer",
    "BoT3",
    "AConv",
    "ADD",
    "ELAN1",
    "CSPStage",
    "CoordAtt",
    "DySample",
    "CARAFE",
    "CoordConv",
    "EMA",
    "RFAConv",
    "RFCBAMConv",
    "RFCAConv",
    "RepViTBlock",
    "LSKblock",
    "FocusedLinearAttention",
    "Bottleneck_FLA",
    "C2f_FLA",
    "PSAFLA",
    "C2f_Context", 
    "ContextGuidedBlock_Down",
    'MultiDilatelocalAttention', 
    'PSAMSDA',
    "ASPP",
    "Bottleneck_Dual",
    "C2f_Dual",
    "Bottleneck_WT",
    "C2f_WT",
    "BasicConv",
    "BasicRFB",
    "BiLevelRoutingAttention",
    "DiverseBranchBlock", 
    "C2f_DBB",
    "SEAM", 
    "MultiSEAM",
    "FFA",
    "MB_TaylorFormer",
    "CPA_arch",
    "iRMB", 
    "C2f_iRMB",
    "HAT",
    "Down_wt",
    "RetinexFormer",
    "C2f_SCConv",
    "C2f_GhostModule_DynamicConv",
    "C2f_ODConv", 
    "ODConv2d",
    "C2f_DWRSeg",
    "SAConv2d", 
    "C2f_SAConv",
    "C2f_MSBlock",
    "C2f_MSBlockv2",
    "OREPA", 
    "C3_OREPA",
    "C2f_OREPA",
    "DynamicConv", 
    "C2f_DynamicConv",
    "IAT",
    "SPDConv",
    "C2f_FasterBlock",
    "C2f_FasterBlock_EMA",
    "C3_Faster_CGLU", 
    "C2f_Faster_CGLU",
    "C3k2_FasterBlock",
    "C2f_SENetV1", 
    "SELayerV1",
    "C2f_SENetV2", 
    "SELayerV2", 
    "PSASENetV2",
    "Light_HGBlock",
    "GSConv",
    "VoVGSCSP",
    "LSKA",
    "RCSOSA",
    "RepVGG",
    "Bi_FPN",
    "RIDNET",
    "ADNet",
    "mn_conv", 
    "InvertedBottleneck", 
    "MobileNetV3_BLOCK",
    "CSPHet",
    "CSPPC",
    "FocalModulation",
    "Zoom_cat", 
    "Add", 
    "ScalSeq", 
    "attention_model",
    "EVCBlock",
    "DSConv2D",
    "C2f_DSConv",
    "VanillaStem", 
    "VanillaBlock",
    "C3_Star", 
    "C3_Star_CAA",
    "C2f_Star", 
    "C2f_Star_CAA",
    "C3_EMBC", 
    "C2f_EMBC",
    "C3_EMSC", 
    "C2f_EMSC",
    "C3_EMSCP", 
    "C2f_EMSCP",
    "C3_UniRepLKNetBlock", 
    "C2f_UniRepLKNetBlock", 
    "C3_DRB", 
    "C2f_DRB",
    "C2f_DAttention",
    "DilatedReparamBlock", 
    "UniRepLKNetBlock",
    "MobileOneBlockv5",
    "MobileOnev5",
    "C3_RetBlock", 
    "C2f_RetBlock",
    "C3_REPVGGOREPA", 
    "C2f_REPVGGOREPA",
    "C3_RFAConv", 
    "C2f_RFAConv", 
    "C3_RFCBAMConv", 
    "C2f_RFCBAMConv", 
    "C3_RFCAConv", 
    "C2f_RFCAConv",
    "C3_RVB", 
    "C2f_RVB",
    "C3_RVB_EMA", 
    "C2f_RVB_EMA",
    "C2f_UIB",
    "PatchMerging", 
    "PatchEmbed", 
    "SwinStage",
    "Concat_BiFPN",
    "C3k2_ConvNeXtV2Block", 
    "C3k_ConvNeXtV2Block",
    "C3k2_WTConv",
    "C3k2_SAConv",
    "C3k2_RepVGG",
    "C2PSA_DAT",
    "DAttentionBaseline",
    "LAE",
    "C2PSA_SENetV2", 
    "SPPFSENetV2",
    "RBFKANConv2d", 
    "ReLUKANConv2d", 
    "KANConv2d", 
    "FasterKANConv2d", 
    "WavKANConv2d", 
    "ChebyKANConv2d", 
    "JacobiKANConv2d", 
    "FastKANConv2d", 
    "GRAMKANConv2d",
    "C2PSA_MSDA",
    "OREPA_2", 
    "C3k2_OREPA_backbone", 
    "C3k2_OREPA_neck",
    "stem",
    "MBConvBlock",
    "C2PSA_CGA", 
    "LocalWindowAttention",
    "C3k2_MLLABlock1", 
    "C3k2_MLLABlock2",
    "C2fMLLABlock",
    "C2PSAMLLA",
    "DiTBlock",
    "C2PSA_DiTBlock",
    "C3k2_DiTBlock",
    "C3k2_UIB",
    "RepHDW", 
    "AVG", 
    "RepHMS", 
    "ConvMS", 
    "UniRepLKNetBlock_pro",
    "SDFM",
    "MANet", 
    "HyperComputeModule",
    "HyperComputeModule_11",
    "ALSS",
    "LCA",
    "EMCAD_block",
    "AAttn",
    "ABlock",
    "A2C2f",
    "MSCAM",
    "MSCAMv2",
    "MSCAMv3", 
    "MSCAMv4",
    "MSCAMv5",
    "LDConv",
    "pvt_v2_b0", 
    "pvt_v2_b1", 
    "pvt_v2_b2",
    "pvt_v2_b3", 
    "pvt_v2_b4", 
    "pvt_v2_b5",
    "MobileNetV1",
    "MobileNetV2_n",
    "MobileNetV2_s",
    "MobileNetV2_m",
    "MobileNetV3_large_n",
    "MobileNetV3_large_s",
    "MobileNetV3_large_m",
    "MobileNetV3_small_n",
    "MobileNetV3_small_s",
    "MobileNetV3_small_m",
    "MobileNetV4ConvLarge", 
    "MobileNetV4ConvSmall", 
    "MobileNetV4ConvMedium", 
    "MobileNetV4HybridMedium", 
    "MobileNetV4HybridLarge",
    "mobile_vit_xx_small",
    "mobile_vit_x_small", 
    "mobile_vit_small",
    "mobile_vit2_xx_small",
    "efficient",
    "efficientnet_v2",
    "Ghostnetv1",
    "GhostNetV2",
    "GhostNet_1_0",
    "convnext_tiny", 
    "convnext_small", 
    "convnext_base," 
    "convnext_large", 
    "convnext_xlarge",
    "convnextv2_atto", 
    "convnextv2_femto", 
    "convnext_pico", 
    "convnextv2_nano", 
    "convnextv2_tiny", 
    "convnextv2_base", 
    "convnextv2_large", 
    "convnextv2_huge",
    "EfficientViT_M0",
    "EfficientViT_M1", 
    "EfficientViT_M2", 
    "EfficientViT_M3", 
    "EfficientViT_M4", 
    "EfficientViT_M5",
    "efficientvit_backbone_b0", 
    "efficientvit_backbone_b1", 
    "efficientvit_backbone_b2", 
    "efficientvit_backbone_b3",
    "repvit_m0_6",
    "repvit_m0_9", 
    "repvit_m1_0", 
    "repvit_m1_1", 
    "repvit_m1_5", 
    "repvit_m2_3",
    "starnet_s050",
    "starnet_s100",
    "starnet_s150",
    "starnet_s1",
    "starnet_s2",
    "starnet_s3",
    "starnet_s4",
    "fasternet_t0", 
    "fasternet_t1", 
    "fasternet_t2", 
    "fasternet_s", 
    "fasternet_m", 
    "fasternet_l",
    "RepLKNet31B", 
    "RepLKNet31L", 
    "RepLKNetXL",
    "unireplknet_a", 
    "unireplknet_f", 
    "unireplknet_p", 
    "unireplknet_n", 
    "unireplknet_t",
    "unireplknet_s", 
    "unireplknet_b", 
    "unireplknet_l", 
    "unireplknet_xl",
    "LSKNET_T", 
    "LSKNET_S",
    "moganet_xtiny",
    "moganet_tiny", 
    "moganet_small", 
    "moganet_base", 
    "moganet_large", 
    "moganet_xlarge",
    "vanillanet_5", 
    "vanillanet_6", 
    "vanillanet_7", 
    "vanillanet_8", 
    "vanillanet_9", 
    "vanillanet_10", 
    "vanillanet_11", 
    "vanillanet_12", 
    "vanillanet_13", 
    "vanillanet_13_x1_5", 
    "vanillanet_13_x1_5_ada_pool",
    "mambaout_femto", 
    "mambaout_kobe", 
    "mambaout_tiny", 
    "mambaout_small", 
    "mambaout_base",
    "RMT_T", 
    "RMT_S", 
    "RMT_B", 
    "RMT_L",
    "revcol_tiny", 
    "revcol_small", 
    "revcol_base", 
    "revcol_large", 
    "revcol_xlarge",
    "SwinTransformer_Tiny", 
    "SwinTransformer_Tiny_c24", 
    "SwinTransformer_Small", 
    "SwinTransformer_Base", 
    "SwinTransformer_Large",
    "swin_transformer_v2_t", 
    "swin_transformer_v2_s", 
    "swin_transformer_v2_b", 
    "swin_transformer_v2_l", 
    "swin_transformer_v2_h", 
    "swin_transformer_v2_g",
    "SwinTransformer_mona_Tiny",
    "SwinTransformer_mona_Small",
    "SwinTransformer_mona_Base",
    "SwinTransformer_mona_Large",
    "SlabSwinTransformer_T", 
    "SlabSwinTransformer_S", 
    "SlabSwinTransformer_B",
    "ShuffleNetG1", 
    "ShuffleNetG2",
    "ShuffleNetG3", 
    "ShuffleNetG4", 
    "ShuffleNetG8",
    "shufflenetv2_05", 
    "shufflenetv2_10", 
    "shufflenetv2_15", 
    "shufflenetv2_20",
    "EMO_1M", 
    "EMO_2M", 
    "EMO_5M", 
    "EMO_6M",
    "EMO2_1M_k5_hybrid",
    "EMO2_1M_k5_hybrid_256", 
    "EMO2_1M_k5_hybrid_512", 
    "EMO2_2M_k5_hybrid", 
    "EMO2_2M_k5_hybrid_256", 
    "EMO2_2M_k5_hybrid_512", 
    "EMO2_5M_k5_hybrid", 
    "EMO2_5M_k5_hybrid_256", 
    "EMO2_5M_k5_hybrid_512", 
    "EMO2_20M_k5_hybrid", 
    "EMO2_20M_k5_hybrid_256", 
    "EMO2_50M_k5_hybrid",
    "VGG11", 
    "VGG13", 
    "VGG16", 
    "VGG19",
    "ResNet18", 
    "ResNet34", 
    "ResNet50", 
    "ResNet101", 
    "ResNet152",
    "resnet18_moe",
    "resnet34_moe", 
    "resnet50_moe", 
    "resnet101_moe", 
    "resnet152_moe",
    "uni_resnet50", 
    "uni_resnet101",
    "sa_resnet50", 
    "sa_resnet101", 
    "sa_resnet152",
    "orthonet34", 
    "orthonet50", 
    "orthonet101", 
    "orthonet152",
    "epsanet50", 
    "epsanet101", 
    "mspanet50",
    "mspanet101",
    "kw_resnet18", 
    "kw_resnet50",
    "overlock_xt", 
    "overlock_t", 
    "overlock_s", 
    "overlock_b",
    "rdnet_tiny", 
    "rdnet_small", 
    "rdnet_base", 
    "rdnet_large",
    "smt_t", 
    "smt_s", 
    "smt_b", 
    "smt_l",
    "GroupMixFormerMiny",
    "GroupMixFormerTiny", 
    "GroupMixFormerSmall",
    "GroupMixFormerBase",
    "GroupMixFormerLarge",
    "pola_pvt_tiny", 
    "pola_pvt_small", 
    "pola_pvt_medium", 
    "pola_pvt_large",
    "nextvit_small", 
    "nextvit_base", 
    "nextvit_large", 
    "focalnet_tiny_srf", 
    "focalnet_tiny_lrf", 
    "focalnet_small_srf", 
    "focalnet_small_lrf", 
    "focalnet_base_srf", 
    "focalnet_base_lrf", 
    "focalnet_large_fl3", 
    "focalnet_large_fl4", 
    "focalnet_xlarge_fl3", 
    "focalnet_xlarge_fl4", 
    "focalnet_huge_fl3", 
    "focalnet_huge_fl4",
    "poolformer_s12", 
    "poolformer_s24", 
    "poolformer_s36", 
    "poolformer_m48", 
    "poolformer_m36",
    "inceptionnext_tiny", 
    "inceptionnext_small", 
    "inceptionnext_base", 
    "inceptionnext_base_384",
    "fastvit_t8", 
    "fastvit_t12", 
    "fastvit_s12", 
    "fastvit_sa12", 
    "fastvit_sa24", 
    "fastvit_sa36", 
    "fastvit_ma36",
    "NFNetF0", 
    "NFNetF1", 
    "NFNetF2", 
    "NFNetF3", 
    "NFNetF4", 
    "NFNetF5", 
    "NFNetF6", 
    "NFNetF7", 
    "DFormerv2_S", 
    "DFormerv2_B", 
    "DFormerv2_L",
    "dfformer_s18",
    "dfformer_s36", 
    "dfformer_m36", 
    "dfformer_b36", 
    "gfformer_s18", 
    "cdfformer_s18", 
    "cdfformer_s36", 
    "cdfformer_m36", 
    "cdfformer_b36", 
    "dfformer_s18_gelu", 
    "dfformer_s18_relu", 
    "dfformer_s18_k2", 
    "dfformer_s18_d8", 
    "dfformer_s18_afno",
    "GhostNet_Reparam",
    "efficientformerv2_s0", 
    "efficientformerv2_s1", 
    "efficientformerv2_s2", 
    "efficientformerv2_l",
    "EdgeVitXXS", 
    "EdgeVitXS",
    "EdgeVitS",
    "GreedyViG_S", 
    "GreedyViG_M", 
    "GreedyViG_B",
    "mobilevigv2_ti", 
    "mobilevigv2_s", 
    "mobilevigv2_m", 
    "mobilevigv2_b",
    "uniformer_light_xxs", 
    "uniformer_light_xs",
    "SwiftFormer_XS",
    "SwiftFormer_S", 
    "SwiftFormer_L1", 
    "SwiftFormer_L3",
    "pvtv2_b0", 
    "pvtv2_b1", 
    "pvtv2_b2", 
    "pvtv2_b2_li", 
    "pvtv2_b3", 
    "pvtv2_b4", 
    "pvtv2_b5",
    "slab_pvt_v2_b0", 
    "slab_pvt_v2_b1", 
    "slab_pvt_v2_b2", 
    "slab_pvt_v2_b2_li", 
    "slab_pvt_v2_b3", 
    "slab_pvt_v2_b4", 
    "slab_pvt_v2_b5",
    "conv2former_n", 
    "conv2former_t", 
    "conv2former_s", 
    "conv2former_b", 
    "conv2former_b_22k", 
    "conv2former_l",
    "LWGANet_L0_1242_e32_k11_GELU", 
    "LWGANet_L1_1242_e64_k11_GELU", 
    "LWGANet_L2_1442_e96_k11_ReLU",
    "hornet_tiny_7x7", 
    "hornet_tiny_gf", 
    "hornet_small_7x7", 
    "hornet_small_gf", 
    "hornet_base_7x7", 
    "hornet_base_gf", 
    "hornet_base_gf_img384",
    "hornet_large_7x7", 
    "hornet_large_gf", 
    "hornet_large_gf_img384",
    "EfficientViM_M1", 
    "EfficientViM_M2", 
    "EfficientViM_M3", 
    "EfficientViM_M4",
    "SHViT_S1", 
    "SHViT_S2", 
    "SHViT_S3", 
    "SHViT_S4",
    "RCViT_XS", 
    "RCViT_S", 
    "RCViT_M", 
    "RCViT_T",
    "gc_vit_xxtiny", 
    "gc_vit_xtiny", 
    "gc_vit_tiny", 
    "gc_vit_tiny2", 
    "gc_vit_small", 
    "gc_vit_small2", 
    "gc_vit_base", 
    "gc_vit_large", 
    "gc_vit_large_224_21k", 
    "gc_vit_large_384_21k", 
    "gc_vit_large_512_21k",
    "convit_tiny_backbone", 
    "convit_small_backbone", 
    "convit_base_backbone",
    "RepVGG_A0", 
    "RepVGG_A1",
    "RepVGG_A2", 
    "RepVGG_B0", 
    "RepVGG_B1", 
    "RepVGG_B1g2", 
    "RepVGG_B1g4", 
    "RepVGG_B2",
    "RepVGG_B2g2", 
    "RepVGG_B2g4", 
    "RepVGG_B3", 
    "RepVGG_B3g2", 
    "RepVGG_B3g4", 
    "RepVGG_D2se",
    "QARepVGG_A0", 
    "QARepVGGV1_A0", 
    "QARepVGGV2_A0", 
    "QARepVGGV2_A0_d01",
    "QARepVGGV2_A0_DW", 
    "QARepVGGV6_A0", 
    "QARepVGG_A0_ReLU6", 
    "QARepVGGV2_A0_PReLU", 
    "QARepVGGV2_A1", 
    "QARepVGGV2_A2", 
    "QARepVGGV2_B0", 
    "QARepVGGV2_B1", 
    "QARepVGGV2_B1g2", 
    "QARepVGGV2_B1g4", 
    "QARepVGGV2_D2se",
    "decouplenet_d0", 
    "decouplenet_d1", 
    "decouplenet_d2",
    "sbcformer_xs", 
    "sbcformer_s", 
    "sbcformer_b", 
    "sbcformer_l",
    "fanet_tiny", 
    "fanet_small",
    "cosnet_tiny", 
    "cosnet_small", 
    "cosnet_base",
    "wtconvnext_tiny", 
    "wtconvnext_small", 
    "wtconvnext_base",
    "wtconvnext_large", 
    "wtconvnext_xlarge",
    "MLLA_Tiny", 
    "MLLA_Small", 
    "MLLA_Base",
    "pkinet_t", 
    "pkinet_s", 
    "pkinet_b",
    "glnet_stl", 
    "glnet_stl_paramslot", 
    "glnet_4g", 
    "glnet_9g", 
    "glnet_16g",
    "RAVLT_T", 
    "RAVLT_S", 
    "RAVLT_B", 
    "RAVLT_L",
    "slak_tiny", 
    "slak_small", 
    "slak_base", 
    "slak_large",
    "svt_s", 
    "svt_b", 
    "svt_l",
    "EViT_Tiny", 
    "EViT_Small", 
    "EViT_Base", 
    "EViT_Large",
    "sgformer_s", 
    "sgformer_m", 
    "sgformer_b",
    "spanet_s", 
    "spanet_m", 
    "spanet_mx", 
    "spanet_b", 
    "spanet_bx",
    "StripMLPNet_LightTiny", 
    "StripMLPNet_Tiny", 
    "StripMLPNet_Small", 
    "StripMLPNet_Base",
    "identityformer_s12", 
    "identityformer_s24", 
    "identityformer_s36", 
    "identityformer_m36", 
    "identityformer_m48", 
    "randformer_s12", 
    "randformer_s24", 
    "randformer_s36", 
    "randformer_m36", 
    "randformer_m48", 
    "poolformerv2_s12", 
    "poolformerv2_s24", 
    "poolformerv2_s36", 
    "poolformerv2_m36", 
    "poolformerv2_m48", 
    "convformer_s18", 
    "convformer_s36", 
    "convformer_m36", 
    "convformer_b36", 
    "caformer_s18", 
    "caformer_s36", 
    "caformer_m36", 
    "caformer_b36",
    "iformer_small", 
    "iformer_base", 
    "iformer_large", 
    "van_b0", 
    "van_b1", 
    "van_b2", 
    "van_b3", 
    "van_b4", 
    "van_b5", 
    "van_b6",
    "vheat_tiny", 
    "vheat_small", 
    "vheat_base",
    "vHeat_MoE_t", 
    "vHeat_MoE_s", 
    "vHeat_MoE_b",
    "LSNet_T", 
    "LSNet_S", 
    "LSNet_B",
    "StripNet_tiny", 
    "StripNet_small",
    "transxnet_tiny", 
    "transxnet_small", 
    "transxnet_base",
    "transnext_micro", 
    "transnext_tiny", 
    "transnext_small", 
    "transnext_base",
    "parcnetv2_xt", 
    "parcnetv2_tiny", 
    "parcnetv2_small", 
    "parcnetv2_base",
    "MALA_T", 
    "MALA_S", 
    "MALA_B", 
    "MALA_L",
    "mpvit_tiny", 
    "mpvit_xsmall",
    "mpvit_small", 
    "mpvit_base",
    "uninext_t", 
    "uninext_s",
    "uninext_b",
    "stvit_small", 
    "stvit_base", 
    "stvit_large",
    "fat_b0", 
    "fat_b1", 
    "fat_b2", 
    "fat_b3",
    "debi_tiny", 
    "debi_small", 
    "debi_base",
    "maxvit_tiny", 
    "maxvit_small", 
    "maxvit_base", 
    "maxvit_large",
    "scalable_vit_s", 
    "scalable_vit_b", 
    "scalable_vit_l",
    "rest_lite", 
    "rest_small", 
    "rest_base", 
    "rest_large", 
    "restv2_tiny", 
    "restv2_small", 
    "restv2_base", 
    "restv2_large",
    "medformer_tiny", 
    "medformer_small", 
    "medformer_base",
    "tiny_vit_5m", 
    "tiny_vit_11m", 
    "tiny_vit_21m",
    "partialnet_s", 
    "partialnet_m", 
    "partialnet_l",
    "waveformer_tiny", 
    "waveformer_small", 
    "waveformer_base",
    "flash_intern_image_t", 
    "flash_intern_image_s", 
    "flash_intern_image_b",
    "dsan_t", 
    "dsan_s", 
    "dsan_b",
    "VanillaNet",
    "UniRepLKNet",
    "OverLoCK",
    "RepViT",
    "FastViT",
    "MobileViG",
    "RepVGGBlock",
    "QARepVGGBlock",
    "C2PSA_HV_LCA",
    "C2PSA_HV_LCA_DynamicTanh",
    "LCA_Concat", 
    "LCA_DynamicTanh_Concat",
    "Conv_DynamicTanh",
    "C2f_MultiOGA", 
    "ChannelAggregationFFN", 
    "MultiOrderGatedAggregation",
    "C2PSA_Agent",
    "C2PSA_KS",
    "MAFOBB",
    "MAFDetect",
    "MAFSegment",
    "MAFPose",
    "FCM", 
    "Pzconv",  
    "FCM_3",
    "FCM_2", 
    "FCM_1", 
    "Down",
    "CSP_EIMS",
    "HRIF",
    "MyConcat4", 
    "MyConcat6", 
    "CST", 
    "MCS",
    "DySnakeConv",
    "C3k2_DSConv",
    "DySnakeRepNCSPELAN4",
    "SFS_Conv",
    "SNI", 
    "GSConvE",
    "GSConvE2", 
    "ESD", 
    "ESD2",
    "DSConv",
    "HyperACE",
    "DownsampleConv",
    "FullPAD_Tunnel",
    "DSC3k2",
    "DSConv",
    "F2SoftHG", 
    "ShapeAlignConv", 
    "MergeConv",
    "Index",
    "LRPCHead",
    "TorchVision",
    "YOLOEDetect",
    "YOLOESegment",
    "MFAM",
    "IEMA",
    "DASI",
    "PST",
    "UPA",
    "MambaNeXt", 
    "IRDCB",
    "VajraV1MerudandaX", 
    "VajraV1AttentionBhag6", 
    "VajraV1MerudandaBhag15",
    
    "PatchEmbed_Faster",
    "PatchMerging_Faster", 
    "FasterNetLayer",
    "Partial_PatchEmbed",
    "Partial_Block", 
    "Partial_Downsample",
    "ParCDown", 
    "ParCBlock",
    "StripDownsample", 
    "StripBlock",
    "StackConvPatchEmbed", 
    "MogaStage", 
    "ConvPatchEmbed",
    "vHeatStem", 
    "vHeatStage", 
    "vHeatDownsample"
)
